import Link from 'next/link';
import { pageMetadata } from '@/lib/seo';
import { ContactEmail, LegalLayout } from '@/components/legal-layout';

export const metadata = pageMetadata('Refund policy', 'Refund eligibility, unused purchases, subscription cancellation, and payment support for SwapThisFace.com.', '/refunds');
const sections = [['scope','Who handles payments'],['unused','Unused purchases'],['problems','Billing and service problems'],['cancel','Canceling renewal'],['request','Requesting a refund'],['rights','Your statutory rights'],['credits','Credits after refunds'],['sandbox','Free trials and sandbox']] as const;
export default function Refunds(){
 return <LegalLayout title="Refund policy" description="This policy applies to SwapThisFace.com, operated by Ibtihaj Uddin, a sole proprietor in Pakistan. Read it alongside our terms and the payment terms shown at checkout." sections={sections}>
  <div className="legal-summary"><p><strong>Unused purchase?</strong> Request a full refund within 14 calendar days if none of the credits from that purchase have been used. This voluntary offer adds to your mandatory legal rights; it does not replace them.</p><p><strong>Stopping a subscription?</strong> Cancel renewal in Plan & credits. Cancellation prevents future renewal payments; it does not automatically refund a previous payment.</p></div>
  <section id="scope"><h2>1. Who handles payments</h2><p>Paddle acts as merchant of record and authorized reseller for paid purchases. Refunds are processed through Paddle, subject to its <a href="https://www.paddle.com/legal/buyer-terms">Buyer Terms</a>, <a href="https://www.paddle.com/legal/refund-policy">Refund Policy</a>, and applicable law. You may contact us or <a href="https://paddle.net">Paddle Buyer Support</a>. If a mandatory right or an additional promise here gives you greater protection, that protection is preserved.</p></section>
  <section id="unused"><h2>2. Our 14-day unused-purchase offer</h2><p>We offer a full refund when you contact us within 14 calendar days of a payment and no credits attributable to that payment have been used for a successful swap. This applies to an initial subscription purchase, a renewal payment, or a standalone credit pack. For subscriptions, eligibility concerns the allowance issued by the payment you want refunded, not usage from every earlier billing period.</p><p>A failed job does not count as successful usage. If credits are reserved for an unfinished job, we will resolve that job before deciding the request. Include your transaction reference so we can check the correct purchase. Do not keep spending the disputed credits while the request is being reviewed.</p><p>Used purchases, upgrade payments, and requests outside this voluntary window are reviewed according to the circumstances, Paddle’s policies, and applicable law. There is no automatic change-of-mind refund for these cases, but this does not exclude rights for faulty or misdescribed services, unauthorized charges, or statutory withdrawal.</p></section>
  <section id="problems"><h2>3. Billing errors and service problems</h2><p>Report duplicate payments, unexpected charges after an effective cancellation, missing purchased credits, or a service that did not deliver the purchased functionality as soon as possible. We will investigate and arrange an appropriate correction or refund through Paddle where due. Our unused-purchase conditions do not exclude these claims.</p><p>Failed or canceled swap jobs release their reserved credit. This is a credit correction, not a cash refund. A completed image may not always match your expectations; contact us with the job reference if there is a material defect. We review faults and quality complaints individually and do not require you to surrender any mandatory remedy.</p></section>
  <section id="cancel"><h2>4. Canceling subscription renewal</h2><p>Use <Link href="/dashboard/billing">Plan & credits</Link> to cancel the next renewal. Your subscription normally continues through the already-paid period, and its unused subscription credits expire at that period’s end. Standalone pack credits remain available without a subscription.</p><p>Cancel before the next renewal to avoid its charge. If cancellation is unavailable, contact us promptly and retain your confirmation or correspondence. Deleting photos, signing out, or stopping use does not cancel a subscription. A refund and a renewal cancellation are different actions; tell us whether you also want renewal stopped.</p></section>
  <section id="request"><h2>5. How to request a refund</h2><ol><li>Email <ContactEmail/> or use <a href="https://paddle.net">Paddle Buyer Support</a>.</li><li>Include your account email, transaction or receipt reference, payment date and amount, and the reason for the request. For a failed delivery, add the job reference if available.</li><li>Never send full card numbers, passwords, or banking credentials. We may request limited information to verify ownership and investigate.</li></ol><p>We aim to acknowledge requests within three business days. That service target does not extend a statutory deadline. Approved refunds are handled by Paddle, ordinarily to the original payment method; Paddle and your payment provider determine the processing and posting time. We will explain the outcome or request any missing information.</p></section>
  <section id="rights"><h2>6. Statutory withdrawal and consumer rights</h2><p>Your location may give you cancellation, withdrawal, repair, replacement, or refund rights beyond this policy. Some jurisdictions provide a 14-day withdrawal period for eligible digital purchases, with exceptions depending on the service and how delivery begins. A legally effective waiver may require specific consent and acknowledgment. Merely reading this page does not waive those rights.</p><p>See Paddle’s <a href="https://www.paddle.com/legal/refund-policy">country-specific refund provisions</a> and the information at checkout. Our usage conditions and voluntary 14-day window never restrict a longer or non-waivable right that applies to you.</p></section>
  <section id="credits"><h2>7. What happens to credits after a refund</h2><p>Credits associated with a fully refunded or reversed purchase are removed or made unavailable. Partial refunds and disputed adjustments may require a manual balance review. Unrelated, validly purchased credits are not automatically forfeited. Contact support if an adjustment appears incorrect.</p><p>We may investigate repeated abusive requests or fraudulent activity, but doing so does not remove legitimate refund or consumer rights.</p></section>
  <section id="sandbox"><h2>8. Free trials and sandbox payments</h2><p>The free guest swap does not collect money or automatically start a subscription. A checkout labeled sandbox uses test payments, not real charges; its test credits do not carry into live billing. There is no monetary refund for a free trial or simulated payment. If you see a real charge you cannot identify, contact us or Paddle.</p></section>
 </LegalLayout>;
}
