import Link from 'next/link';

export function PhotoSwapGuide() {
  return <section className="photo-guide" aria-labelledby="photo-guide-title"><div className="section-heading"><div><div className="eyebrow">CHOOSE YOUR PHOTOS</div><h2 id="photo-guide-title">What makes a realistic photo face swap?</h2></div><p>Start with images that work together.</p></div><p className="guide-intro">An AI photo face swap uses a processing model to place a source face into a target image. A natural-looking result depends on both photos and the model. These photo choices give a face swap editor a better starting point; they do not guarantee a particular result.</p><div className="steps-grid"><article className="step-card"><h3>Match the face angle</h3><p>Choose photos with similar head positions. A straight-on portrait is easier to match with another straight-on face than with a side profile.</p></article><article className="step-card"><h3>Use clear, even lighting</h3><p>Start with a sharp face photo without heavy filters. Similar lighting and fewer shadows help you assess whether the finished image looks consistent.</p></article><article className="step-card"><h3>Keep one face visible</h3><p>Use a source photo and a target photo with one clearly visible face each. Avoid sunglasses, hands covering the face, and very small or blurred faces.</p></article></div><p className="guide-links">Ready to prepare your images? <Link href="/face-swap">Open the photo face swap studio</Link> or review our <Link href="/privacy">photo storage and privacy policy</Link>.</p></section>;
}

export function PhotoSwapFaq() {
  return <section className="faq photo-faq" aria-labelledby="photo-faq-title"><h2 id="photo-faq-title">Photo face swap questions</h2><details><summary>How do I swap a face from one photo to another?</summary><p>Choose your source face photo, then upload the target photo where you want that face to appear. Submit the job and compare or download the result. SwapThisFace.com currently runs a labeled mock preview while the real face-swap API is being connected.</p></details><details><summary>Can I try a face swap online without signing up?</summary><p>The guest offer is one successful swap without an account. It is not unlimited free access. After that, Google sign-in, an active subscription, and available credits are required. In staging, a successful mock preview uses the guest trial. See <Link href="/pricing">plans and credit details</Link>.</p></details><details><summary>Will my result look realistic?</summary><p>Clear photos with similar angles and lighting can help, but output quality depends on the processing provider. We cannot promise photorealistic results. The current staging preview does not perform an AI face swap, so it should not be used to judge final quality.</p></details><details><summary>Can I swap multiple faces, group photos, or videos?</summary><p>This version supports one source face photo and one target photo. Multiple-face swaps, video, GIFs, and live camera swaps are not supported.</p></details><details><summary>Can I use the photo editor on my phone?</summary><p>Use the website in your mobile browser and choose JPG, PNG, or WebP images up to 10 MB each. No app or APK download is required. If your phone saves HEIC photos, export them in a supported format first.</p></details><details><summary>Is it safe to upload someone’s face?</summary><p>Only upload images you have permission to use, including permission from the people shown. Uploads are private within the app, but they are processed by our service infrastructure. Originals expire after 24 hours; see the <Link href="/privacy">privacy policy</Link> for retention, access, and deletion details.</p></details></section>;
}
