'use client';
import { useEffect, useRef, useState } from 'react';
import { api, errorMessage } from './api-client';
import { useAccount } from './account-provider';
export type PlanQuote={updatedAt:string;dueNow:string;recurring:string;currency:string;nextBilledAt:string|null};
function money(amount:string,currency:string){const format=new Intl.NumberFormat('en',{style:'currency',currency});return format.format(Number(amount)/10**(format.resolvedOptions().maximumFractionDigits??2));}
export function PlanChange({disabled=false}:{disabled?:boolean}){
 const {refresh,syncBilling}=useAccount(); const dialog=useRef<HTMLDialogElement>(null);
 const [quote,setQuote]=useState<PlanQuote|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{if(quote)dialog.current?.showModal();},[quote]);
 async function preview(){setBusy(true);setError('');try{setQuote(await api<PlanQuote>('/api/billing/subscription',{method:'POST',body:JSON.stringify({action:'preview',planCode:'monthly'})}));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function confirm(){setBusy(true);setError('');try{await api('/api/billing/subscription',{method:'POST',body:JSON.stringify({action:'upgrade',planCode:'monthly',updatedAt:quote?.updatedAt,maxDueNow:quote?.dueNow,currency:quote?.currency})});syncBilling();dialog.current?.close();setQuote(null);setMessage('Plan change submitted. Your plan and credits will update after payment confirmation.');await refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <><button className="button button-lime" disabled={disabled||busy} onClick={preview}>{busy?'Please wait…':'Upgrade to monthly'}</button>{message&&<p role="status" className="inline-notice">{message}</p>}{error&&!quote&&<p role="alert" className="inline-notice">{error}</p>}<dialog className="billing-dialog" ref={dialog} onCancel={event=>{if(busy)event.preventDefault();else setQuote(null);}}>{quote&&<><h2>Review your monthly upgrade</h2><dl className="billing-summary"><div><dt>Estimated charge now</dt><dd>{money(quote.dueNow,quote.currency)}</dd></div><div><dt>Then every month</dt><dd>{money(quote.recurring,quote.currency)}</dd></div><div><dt>Next renewal</dt><dd>{quote.nextBilledAt?new Date(quote.nextBilledAt).toLocaleDateString():'Shown after confirmation'}</dd></div></dl><p>Paddle prorates the change. Your new monthly allowance replaces unused weekly credits after payment is confirmed. Any partial period receives a proportional allowance. Purchased credit packs stay unchanged.</p>{error&&<p role="alert">{error}</p>}<div className="billing-actions"><button className="button button-lime" disabled={busy} onClick={confirm}>{busy?'Updating…':'Confirm & pay'}</button><button className="button button-outline" disabled={busy} onClick={()=>{dialog.current?.close();setQuote(null);setError('');}}>Keep weekly plan</button></div></>}</dialog></>;
}
