'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Check, ArrowUpRight, LoaderCircle, CircleAlert, Zap } from './icons';
import { api, ApiError, errorMessage } from './api-client';

type Plan={code:string;name:string;interval:string;configured:boolean;includedCredits:number|null;amount?:number|null;unitAmount?:number|null;currency?:string|null};
type Pack={code:string;name:string;configured:boolean;credits:number|null;amount?:number|null;currency?:string|null};
type Catalog={environment?:string;subscriptions:Plan[];creditPacks:Pack[]};
const defaults:Plan[]=[{code:'weekly',name:'Weekly',interval:'week',configured:false,includedCredits:null},{code:'monthly',name:'Monthly',interval:'month',configured:false,includedCredits:null}];
const descriptions:Record<string,string>={weekly:'For a little creative adventure.',monthly:'Make room for more possibilities.',yearly:'A full year of fresh perspectives.'};
export function PricingCards(){
 const [catalog,setCatalog]=useState<Catalog>({subscriptions:defaults,creditPacks:[]});const [busy,setBusy]=useState('');const [error,setError]=useState('');const [pending,setPending]=useState(false);
 useEffect(()=>{api<Catalog>('/api/billing/plans').then(setCatalog).catch(e=>setError(errorMessage(e)));},[]);
 async function checkout(code:string,kind:'plan'|'pack'){
  setBusy(code);setError('');setPending(false);try{const data=await api<{url:string}>(kind==='plan'?'/api/billing/checkout':'/api/billing/credits',{method:'POST',body:JSON.stringify(kind==='plan'?{planCode:code}:{packCode:code})});window.location.assign(data.url);}catch(e){if(e instanceof ApiError&&e.status===401){window.location.assign('/login?next=/pricing');return;}setPending(e instanceof ApiError&&e.code==='checkout_pending');setError(errorMessage(e));}finally{setBusy('');}
 }
 const hasLivePlans=catalog.subscriptions.some(plan=>plan.configured);
 return <>{catalog.environment==='sandbox'&&hasLivePlans&&<p className="inline-notice" role="status">Sandbox testing: checkout accepts test payments only. Test credits will not carry over when live billing opens.</p>}<div className="pricing-grid" style={{gridTemplateColumns:"repeat(auto-fit, minmax(min(100%, 320px), 1fr))"}}>{catalog.subscriptions.map(plan=>{
 const amount=plan.unitAmount??plan.amount;const formatted=amount!=null&&plan.currency?new Intl.NumberFormat('en',{style:'currency',currency:plan.currency}).format(amount/100):null;
 return <article key={plan.code} className={`price-card ${plan.code==='monthly'?'featured':''}`}>{plan.code==='monthly'&&<span className="plan-badge">A LITTLE EVERY MONTH</span>}<h2>{plan.name}</h2><p>{descriptions[plan.code]}</p><div className={`price-amount ${formatted?'':'unset'}`}>{formatted??(plan.configured?'See checkout':'Coming soon')}{formatted&&<small>/{plan.interval}</small>}</div><p>{plan.includedCredits!=null?`${plan.includedCredits} credits every ${plan.interval}`:'Credit allowance loading'}</p><ul><li><Check/>Single-face photo swaps</li><li><Check/>Private photos and saved history</li><li><Check/>Download your results</li><li><Check/>Buy extra credits when you need them</li><li><Check/>Cancel future renewals anytime</li></ul><button onClick={()=>checkout(plan.code,'plan')} disabled={!plan.configured||Boolean(busy)} className={`button button-full ${plan.code==='monthly'?'button-lime':'button-outline'}`}>{busy===plan.code?<LoaderCircle size={15} className="spin"/>:<ArrowUpRight size={15}/>} {plan.configured?`Choose ${plan.name.toLowerCase()}`:'Not available yet'}</button></article>;
 })}</div><p className="pricing-footnote">One credit per successful swap. Failed swaps release your credit.<br/>{!hasLivePlans?'Purchases are not open yet. Prices shown are in USD; applicable taxes are shown at checkout.':'Subscriptions renew automatically. Manage or cancel future renewals from your billing page.'}</p>
 {error&&<div role="alert" className="inline-notice"><CircleAlert size={14} style={{verticalAlign:'middle',marginRight:7}}/>{error}{pending&&<button className="button button-outline" onClick={async()=>{try{await api('/api/billing/cancel-checkout',{method:'POST'});setPending(false);setError('Pending checkout canceled. You can choose another offer.');}catch(e){setError(errorMessage(e));}}}>Cancel pending checkout</button>}</div>}
 <div className="credit-pack"><div><h3>A little extra inspiration?</h3><p>Buy credits whenever you need them—no subscription required. Purchased credits do not expire.</p></div>{catalog.creditPacks.length>0?<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{catalog.creditPacks.map(pack=><button key={pack.code} className="button button-outline" disabled={!pack.configured||Boolean(busy)} onClick={()=>checkout(pack.code,'pack')}><Zap size={14}/>{busy===pack.code?'Opening…':`${pack.credits} swaps — ${new Intl.NumberFormat("en",{style:"currency",currency:pack.currency??"USD"}).format((pack.amount??0)/100)}`}</button>)}</div>:<span className="tiny-tag"><Zap size={12}/>CREDIT PACKS COMING SOON</span>}</div></>;
}
