'use client';
import { useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import { ImagePlus,Upload,Sparkles,ShieldCheck,Check,LoaderCircle,CircleAlert,ArrowUpRight,Download,RefreshCw,MoveHorizontal,Layers } from './icons';
import { api,ApiError,errorMessage } from './api-client';
type Job={id:string;status:string;resultAssetId?:string|null;isMock?:boolean;errorMessage?:string|null};
function normalize(raw:any):Job{return {...raw,status:raw.status??raw.state,resultAssetId:raw.resultAssetId??raw.result_asset_id,errorMessage:raw.errorMessage??raw.error_message,isMock:raw.isMock??raw.result_metadata?.mock};}
const terminal=new Set(['succeeded','failed','canceled']);
export function SwapStudio(){
 const [source,setSource]=useState<File|null>(null);const [target,setTarget]=useState<File|null>(null);const [targetPreview,setTargetPreview]=useState('');const [job,setJob]=useState<Job|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [needsAccount,setNeedsAccount]=useState(false);const [phase,setPhase]=useState('');const pollAbort=useRef<AbortController|null>(null);const requestKey=useRef<string|null>(null);
 useEffect(()=>{if(!target){setTargetPreview('');return;}const url=URL.createObjectURL(target);setTargetPreview(url);return()=>URL.revokeObjectURL(url);},[target]);
 useEffect(()=>()=>pollAbort.current?.abort(),[]);
 const resultUrl=job?.resultAssetId?`/api/assets/${encodeURIComponent(job.resultAssetId)}/download`:'';
 async function run(){if(!source||!target||busy)return;setBusy(true);setError('');setNeedsAccount(false);setPhase('Preparing your studio…');setJob(null);const controller=new AbortController();pollAbort.current=controller;
  try{await api('/api/guest',{method:'POST',signal:controller.signal});setPhase('Uploading your photos…');
   const upload=async(file:File,kind:string)=>{const body=new FormData();body.append('file',file);body.append('kind',kind);const data=await api<{asset?:{id:string};id?:string}>('/api/uploads',{method:'POST',body,signal:controller.signal});const id=data.asset?.id??data.id;if(!id)throw new Error('The upload could not be saved. Please try again.');return id;};
   const sourceAssetId=await upload(source,'source');const targetAssetId=await upload(target,'target');setPhase('Creating your swap…');requestKey.current??=crypto.randomUUID();
   const response=await api<{job:Job}>('/api/swaps',{method:'POST',body:JSON.stringify({sourceAssetId,targetAssetId,requestKey:requestKey.current}),signal:controller.signal});let current=normalize(response.job);setJob(current);
   for(let attempt=0;!terminal.has(current.status)&&attempt<120;attempt++){setPhase(current.status==='queued'?'Your swap is in the queue…':'Working on your photo…');await new Promise<void>((resolve,reject)=>{const abort=()=>{clearTimeout(timer);reject(new DOMException('Aborted','AbortError'));};const timer=setTimeout(()=>{controller.signal.removeEventListener('abort',abort);resolve();},Math.min(1500+attempt*100,5000));controller.signal.addEventListener('abort',abort,{once:true});});const update=await api<{job:Job}>(`/api/swaps/${current.id}`,{signal:controller.signal});current=normalize(update.job);setJob(current);}
   if(current.status==='failed'||current.status==='canceled'){requestKey.current=null;throw new Error(current.errorMessage||'This swap could not be completed. Your credit or free trial has been released.');}if(!terminal.has(current.status))throw new Error('Your swap is still processing. Check your history shortly; do not submit it again.');setPhase('');requestKey.current=null;
  }catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;setError(errorMessage(e));if(e instanceof ApiError&&['trial_used','subscription_required','auth_required','unauthorized','payment_required','TRIAL_USED','SUBSCRIPTION_REQUIRED'].includes(e.code??''))setNeedsAccount(true);}finally{setBusy(false);}}
 function reset(){setJob(null);setError('');setPhase('');requestKey.current=null;}
 return <div className="studio-card"><div className="studio-topbar"><span className="studio-topbar-title"><Layers size={15}/>Your face-swap studio <span className="tiny-tag">PHOTO</span></span><span className="studio-topbar-meta"><ShieldCheck size={12}/>Just for you</span></div><div className="studio-main"><div><div className="upload-column-heading"><span className="number-circle">1</span>Your face</div><UploadZone file={source} label="Upload your face" description="A clear, front-facing photo" disabled={busy} onChange={file=>{setSource(file);reset();}} onError={setError}/><p className="upload-help"><Check size={11}/>One face, good lighting, no sunglasses</p></div><div><div className="upload-column-heading"><span className="number-circle">2</span>Your new look</div><UploadZone file={target} label="Upload a target photo" description="The photo you want to step into" disabled={busy} onChange={file=>{setTarget(file);reset();}} onError={setError}/><p className="upload-help"><Check size={11}/>Choose a photo with one visible face</p></div><div className="preview-column"><div className="upload-column-heading"><Sparkles size={15}/>The new you {job?.status==='succeeded'&&<span className="tiny-tag">PREVIEW</span>}</div>{job?.status==='succeeded'&&resultUrl?<><Comparison before={targetPreview} after={resultUrl}/><div className="result-actions"><a className="button button-dark" href={resultUrl} download><Download size={13}/>Download</a><button className="button button-outline" onClick={reset}><RefreshCw size={13}/>Start again</button></div></>:<><div className="result-empty">{busy?<LoaderCircle size={31} strokeWidth={1.3} className="spin"/>:<Sparkles size={31} strokeWidth={1.2}/>}<p aria-live="polite">{busy?phase:'A new possibility awaits'}</p><p className="result-subtext">{busy?'You can stay here while we work.':'Your result will appear right here'}</p></div><button className="button button-lime swap-action" disabled={!source||!target||busy} onClick={run}>{busy?<LoaderCircle size={14} className="spin"/>:<Sparkles size={14}/>} {busy?'Creating your swap…':'Swap my face'}{!busy&&<ArrowUpRight size={14}/>}</button><p className="credits-note">Your first swap is on us. No sign-up needed.</p></>}</div></div><div className="setup-notice"><CircleAlert size={14}/><span>Development preview: the face-swap API isn’t connected yet. Test jobs return a labeled preview of the target photo, not a real face swap.</span></div>{error&&<div role="alert" className="setup-notice error-notice"><CircleAlert size={14}/><span>{error}{needsAccount&&<> <Link className="text-link" href="/login">Sign in to continue <ArrowUpRight size={12}/></Link></>}</span></div>}<div className="studio-bottom"><span><ShieldCheck size={12}/>Your uploads are private. You’re always in control.</span><span>JPG, PNG or WebP · Up to 10 MB per photo</span></div></div>;
}
function UploadZone({file,label,description,disabled,onChange,onError}:{file:File|null;label:string;description:string;disabled:boolean;onChange:(file:File)=>void;onError:(message:string)=>void}){const input=useRef<HTMLInputElement>(null);const [preview,setPreview]=useState('');const [dragging,setDragging]=useState(false);useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);function choose(candidate:File|undefined){if(!candidate)return;if(!['image/jpeg','image/png','image/webp'].includes(candidate.type)){onError('Choose a JPG, PNG, or WebP photo.');return;}if(candidate.size>10*1024*1024){onError('Your photo is too large. Choose one under 10 MB.');return;}onError('');onChange(candidate);}return <div><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" disabled={disabled} tabIndex={-1} aria-label={label} style={{display:'none'}} onChange={e=>{choose(e.target.files?.[0]);e.target.value='';}}/><button type="button" className={`upload-drop ${dragging?'dragging':''}`} disabled={disabled} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();if(!disabled)setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(!disabled)choose(e.dataTransfer.files[0]);}} aria-label={file?`Replace ${label.toLowerCase()}: ${file.name}`:label}>{preview?<><img className="uploaded-photo" src={preview} alt={label==='Upload your face'?'Your uploaded face':'Your selected target photo'}/><span className="upload-replace">Click to replace photo</span></>:<><div className="upload-icon"><ImagePlus size={22} strokeWidth={1.5}/></div><strong>{label}</strong><span>{description}<br/>or drag and drop here</span><span className="browse-label"><Upload size={10} style={{display:'inline',verticalAlign:'middle',marginRight:5}}/>Browse photos</span></>}</button></div>;}
function Comparison({before,after}:{before:string;after:string}){const [position,setPosition]=useState(50);return <div className="compare-view"><img src={before} alt="Original target photo"/><div className="compare-after" style={{clipPath:`inset(0 0 0 ${position}%)`}}><img src={after} alt="Generated preview"/></div><span className="compare-label before">Original</span><span className="compare-label after">Preview</span><div className="compare-divider" style={{left:`${position}%`}}><span className="compare-handle"><MoveHorizontal size={14}/></span></div><input type="range" min={0} max={100} value={position} onChange={e=>setPosition(Number(e.target.value))} aria-label="Compare original and result"/></div>;}
