import Link from 'next/link';
import { pageMetadata, absoluteUrl, serializeJsonLd } from '@/lib/seo';
import { PhotoSwapGuide } from '@/components/photo-swap-guide';
import { PhotoPossibilities, PhotoIdeas, PhotoEditingExplainer, HomeFaq } from '@/components/home-content';
import { StudioInvitation } from '@/components/site-shell';
import { ArrowUpRight, ArrowRight, Sparkles, ShieldCheck, Layers, ImagePlus, Zap } from '@/components/icons';
import { SwapStudio } from '@/components/swap-studio';

export const metadata = pageMetadata('Photo Face Swap Online', 'Put your face in another photo with our online face swap studio. Learn which photos work best, explore creative ideas, and try one guest preview without signing up.', '/');

export default function Home() {
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:serializeJsonLd({'@context':'https://schema.org','@type':'WebSite',name:'SwapThisFace.com',url:absoluteUrl('/'),publisher:{'@type':'Organization',name:'Codeflow Solutions'}})}}/>
 <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="status-dot" /> PHOTO FACE SWAP ONLINE</div><h1>Put your face<br />in a new <span className="serif-word">photo.</span><span className="headline-spark">✳</span></h1><p className="hero-description">Start with your selfie and a photo you’d like to step into. Our online photo face swap studio brings both images into one simple workflow—upload, compare, and download.</p><StudioInvitation /><div className="hero-benefits"><span><ShieldCheck size={16} /> Private by default</span><span><Zap size={16} /> A few simple steps</span></div></div>
 <div className="hero-art" aria-label="Creative portrait inspiration"><span className="art-grid" /><div className="portrait-card portrait-back"><img src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=650&auto=format&fit=crop&q=85" alt="Portrait inspiration in blue and purple lighting" /><span className="photo-tag">A FRESH PERSPECTIVE</span></div><div className="portrait-card portrait-front"><img src="https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=650&auto=format&fit=crop&q=85" alt="Portrait inspiration against a dark backdrop" /><span className="photo-tag"><span className="white-dot" /> YOUR NEXT WHAT-IF</span></div><span className="floating-label"><Sparkles size={16} /> A little change. A new story.</span><span className="art-star">✳</span><span className="art-caption">PORTRAIT INSPIRATION · NOT SWAP RESULTS</span></div></section>
 <section className="studio-section" id="studio"><div className="wrap"><div className="section-heading"><div><div className="eyebrow">THE CREATIVE PART</div><h2>Your photo face swap starts here<span className="lime-text">.</span></h2></div><p>Two photos. One fresh perspective.</p></div><SwapStudio /></div></section>
 <section className="how-section wrap"><div className="section-heading"><div><div className="eyebrow">LESS WORK. MORE WHAT-IF.</div><h2>How to swap a face between two photos.</h2></div><Link className="text-link" href="/face-swap">Open the studio <ArrowUpRight size={17} /></Link></div><div className="steps-grid"><Step number="01" icon={<ImagePlus />} title="Start with your face" text="Choose a clear, front-facing photo. Good light makes a good starting point." /><Step number="02" icon={<Layers />} title="Pick a new perspective" text="Upload the photo you want to step into. Choose an image with one visible face." /><Step number="03" icon={<Sparkles />} title="Make it your own" text="Create your swap, compare the result, and download it. Keep exploring from your studio." /></div></section>
 <PhotoPossibilities /><PhotoIdeas /><div className="wrap"><PhotoSwapGuide /></div><PhotoEditingExplainer /><HomeFaq /><section className="bottom-cta wrap"><div><div className="eyebrow">GO ON. GET CURIOUS.</div><h2>A new look is a photo away.</h2><p>Bring two photos and explore your next look.</p></div><Link href="/face-swap" className="button button-dark">Let’s create <ArrowRight size={18} /></Link></section>
 </>;
}
function Step({number,icon,title,text}:{number:string;icon:React.ReactNode;title:string;text:string}) { return <article className="step-card"><div className="step-top"><span className="step-icon">{icon}</span><span className="step-number">{number}</span></div><h3>{title}</h3><p>{text}</p></article>; }
